name: Pack Build

on:
  push:
    branches:
      # - never # Skip the workflow for debugging purposes;
      # - implement/package/ci
      - develop # Keep this for a time being
      - master
    # paths:
    #   - ".github/workflows/food-service.yml"
    #   - "implementation/**"
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }} # NB: Cannot use 'GITHUB_' prefix

    name: Test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # NB: Usage package depends on the parent package using `file:` dependency
      # Provide it in `.delivery` folder.
      - name: Run Package Build
        run: npm run package:build

      - name: Install dependencies for .usage subfolder
        working-directory: ./.usage
        run: npm install

      - name: Run tests and collect coverage
        # NB: See https://app.codecov.io/gh/WhereJuly/62-http-convenience-pack/tests/new
        # NB: See https://app.codecov.io/gh/WhereJuly/62-http-convenience-pack/new
        # Here need to run my tests with coverage and reporter JUNIT
        # test:foundation --reporter=junit --outputFile=test-report.junit.xml
        # run: npm run test:foundation -- \
        #   --reporter=junit --outputFile=test-report.junit.xml --reporter=verbose
        run: npm run test:foundation -- --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
